-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 10:42:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero` VARCHAR(5) NULL,
  `Colonia` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `IdCliente` INT NOT NULL,
  PRIMARY KEY (`idDireccion`, `IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegistroCliente` (
  `idRegistroCliente` INT NOT NULL,
  `DPI` INT NULL,
  `Nombre` VARCHAR(20) NULL,
  `Direccion` VARCHAR(30) NULL,
  `Telefono` VARCHAR(8) NULL,
  PRIMARY KEY (`idRegistroCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `DPI` INT NULL,
  `Nombre` VARCHAR(20) NULL,
  `Direccion` VARCHAR(30) NULL,
  `Telefono` VARCHAR(8) NULL,
  `Direccion_idDireccion` INT NOT NULL,
  `Direccion_IdCliente` VARCHAR(45) NOT NULL,
  `RegistroCliente_idRegistroCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Direccion_idDireccion`, `Direccion_IdCliente`, `RegistroCliente_idRegistroCliente`),
  INDEX `fk_Cliente_Direccion1_idx` (`Direccion_idDireccion` ASC, `Direccion_IdCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_RegistroCliente1_idx` (`RegistroCliente_idRegistroCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion` , `Direccion_IdCliente`)
    REFERENCES `mydb`.`Direccion` (`idDireccion` , `IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_RegistroCliente1`
    FOREIGN KEY (`RegistroCliente_idRegistroCliente`)
    REFERENCES `mydb`.`RegistroCliente` (`idRegistroCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  `Descripción` TEXT(50) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegistroProducto` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  `PrecioActual` DECIMAL(10) NULL,
  `Stock` INT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  `PrecioActual` DECIMAL(10) NULL,
  `Stock` INT NULL,
  `IdCategoria` INT NOT NULL,
  `IdProveedor` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `RegistroProducto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `IdCategoria`, `IdProveedor`, `Categoria_idCategoria`, `RegistroProducto_idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Producto_RegistroProducto1_idx` (`RegistroProducto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_RegistroProducto1`
    FOREIGN KEY (`RegistroProducto_idProducto`)
    REFERENCES `mydb`.`RegistroProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `DPI` INT NULL,
  `Direccion` VARCHAR(30) NULL,
  `Telefono` VARCHAR(14) NULL,
  `Paginaweb` VARCHAR(20) NULL,
  `Nombre` VARCHAR(20) NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_IdCategoria` INT NOT NULL,
  `Producto_IdProveedor` INT NOT NULL,
  PRIMARY KEY (`idProveedor`, `Producto_idProducto`, `Producto_IdCategoria`, `Producto_IdProveedor`),
  INDEX `fk_Proveedor_Producto_idx` (`Producto_idProducto` ASC, `Producto_IdCategoria` ASC, `Producto_IdProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_Producto`
    FOREIGN KEY (`Producto_idProducto` , `Producto_IdCategoria` , `Producto_IdProveedor`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `IdCategoria` , `IdProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegistroVenta` (
  `idVenta` INT NOT NULL,
  `Fecha` DATE NULL,
  `Descuento` DECIMAL(10) NULL,
  `MontoFinal` DECIMAL(10) NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `Fecha` DATE NULL,
  `IdCliente` INT NOT NULL,
  `Descuento` DECIMAL(10) NULL,
  `MontoFinal` DECIMAL(10) NULL,
  `RegistroVenta_idVenta` INT NOT NULL,
  `RegistroVenta_IdCliente` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `IdCliente`, `RegistroVenta_idVenta`, `RegistroVenta_IdCliente`),
  INDEX `fk_Venta_RegistroVenta1_idx` (`RegistroVenta_idVenta` ASC, `RegistroVenta_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_RegistroVenta1`
    FOREIGN KEY (`RegistroVenta_idVenta`)
    REFERENCES `mydb`.`RegistroVenta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Venta` (
  `Cliente_DPI` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `Venta_IdCliente` INT NOT NULL,
  PRIMARY KEY (`Cliente_DPI`, `Cliente_idCliente`, `Venta_idVenta`, `Venta_IdCliente`),
  INDEX `fk_Cliente_has_Venta_Venta1_idx` (`Venta_idVenta` ASC, `Venta_IdCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Venta_Cliente1_idx` (`Cliente_DPI` ASC, `Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Venta_Cliente1`
    FOREIGN KEY (`Cliente_DPI` , `Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`DPI` , `idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Venta_Venta1`
    FOREIGN KEY (`Venta_idVenta` , `Venta_IdCliente`)
    REFERENCES `mydb`.`Venta` (`idVenta` , `IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor_has_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor_has_Venta` (
  `Proveedor_idProveedor` INT NOT NULL,
  `Proveedor_DPI` INT NOT NULL,
  `Proveedor_Producto_idProducto` INT NOT NULL,
  `Proveedor_Producto_IdCategoria` INT NOT NULL,
  `Proveedor_Producto_IdProveedor` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `Venta_IdCliente` INT NOT NULL,
  PRIMARY KEY (`Proveedor_idProveedor`, `Proveedor_DPI`, `Proveedor_Producto_idProducto`, `Proveedor_Producto_IdCategoria`, `Proveedor_Producto_IdProveedor`, `Venta_idVenta`, `Venta_IdCliente`),
  INDEX `fk_Proveedor_has_Venta_Venta1_idx` (`Venta_idVenta` ASC, `Venta_IdCliente` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Venta_Proveedor1_idx` (`Proveedor_idProveedor` ASC, `Proveedor_DPI` ASC, `Proveedor_Producto_idProducto` ASC, `Proveedor_Producto_IdCategoria` ASC, `Proveedor_Producto_IdProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_has_Venta_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor` , `Proveedor_DPI` , `Proveedor_Producto_idProducto` , `Proveedor_Producto_IdCategoria` , `Proveedor_Producto_IdProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor` , `DPI` , `Producto_idProducto` , `Producto_IdCategoria` , `Producto_IdProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Venta_Venta1`
    FOREIGN KEY (`Venta_idVenta` , `Venta_IdCliente`)
    REFERENCES `mydb`.`Venta` (`idVenta` , `IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
