-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 11:56:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avion` (
  `idAvion` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Capacidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aeropuerto` (
  `id_aeropuerto` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Avion_idAvion` INT NOT NULL,
  PRIMARY KEY (`id_aeropuerto`, `Avion_idAvion`),
  INDEX `fk_Aeropuerto_Avion_idx` (`Avion_idAvion` ASC) VISIBLE,
  CONSTRAINT `fk_Aeropuerto_Avion`
    FOREIGN KEY (`Avion_idAvion`)
    REFERENCES `mydb`.`Avion` (`idAvion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LineaAerea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LineaAerea` (
  `idLineaAerea` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Contacto` VARCHAR(45) NULL,
  `Lugar_de_operaciones` VARCHAR(45) NULL,
  `Anio_de_inicio_de_labores` INT NULL,
  `Estado` VARCHAR(45) NULL,
  `Clasificacion_de_servicio` VARCHAR(45) NULL,
  PRIMARY KEY (`idLineaAerea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EscalaTecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EscalaTecnica` (
  `idEscalaTecnica` INT NOT NULL,
  `Lugar` VARCHAR(45) NULL,
  `Duracion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEscalaTecnica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vuelo` (
  `idVuelo` INT NOT NULL,
  `Fecha` DATE NULL,
  `Plazas_disponibles` INT NULL,
  `Plazas_ocupadas` INT NULL,
  `Destino` VARCHAR(45) NULL,
  `EscalaTecnica_idEscalaTecnica` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_Vuelo_EscalaTecnica1_idx` (`EscalaTecnica_idEscalaTecnica` ASC) VISIBLE,
  CONSTRAINT `fk_Vuelo_EscalaTecnica1`
    FOREIGN KEY (`EscalaTecnica_idEscalaTecnica`)
    REFERENCES `mydb`.`EscalaTecnica` (`idEscalaTecnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProgramaVuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProgramaVuelo` (
  `idProgramaVuelo` INT NOT NULL,
  `Numero_de_vuelo` INT NULL,
  `Dias_de_vuelo` VARCHAR(45) NULL,
  `TripilacionPiloto` VARCHAR(45) NULL,
  `TripulacionCo-piloto` VARCHAR(45) NULL,
  `TripulacionAzafatas` VARCHAR(45) NULL,
  `Aeropuerto_id_aeropuerto` INT NOT NULL,
  `Aeropuerto_Avion_idAvion` INT NOT NULL,
  `LineaAerea_idLineaAerea` INT NOT NULL,
  `Vuelo_idVuelo` INT NOT NULL,
  PRIMARY KEY (`idProgramaVuelo`),
  INDEX `fk_ProgramaVuelo_Aeropuerto1_idx` (`Aeropuerto_id_aeropuerto` ASC, `Aeropuerto_Avion_idAvion` ASC) VISIBLE,
  INDEX `fk_ProgramaVuelo_LineaAerea1_idx` (`LineaAerea_idLineaAerea` ASC) VISIBLE,
  INDEX `fk_ProgramaVuelo_Vuelo1_idx` (`Vuelo_idVuelo` ASC) VISIBLE,
  CONSTRAINT `fk_ProgramaVuelo_Aeropuerto1`
    FOREIGN KEY (`Aeropuerto_id_aeropuerto` , `Aeropuerto_Avion_idAvion`)
    REFERENCES `mydb`.`Aeropuerto` (`id_aeropuerto` , `Avion_idAvion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProgramaVuelo_LineaAerea1`
    FOREIGN KEY (`LineaAerea_idLineaAerea`)
    REFERENCES `mydb`.`LineaAerea` (`idLineaAerea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProgramaVuelo_Vuelo1`
    FOREIGN KEY (`Vuelo_idVuelo`)
    REFERENCES `mydb`.`Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
