-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 22:51:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `Correo_electronico` VARCHAR(45) NULL,
  `genero` ENUM('M', 'F', 'OTRO') NOT NULL,
  `fecha_nac` DATE NULL,
  `Usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `contacto` VARCHAR(20) NULL,
  `Usuarioscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `id_principal` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publicaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Categorias_idCategorias` INT NOT NULL,
  PRIMARY KEY (`idPublicaciones`),
  INDEX `fk_Publicaciones_Usuarios_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Publicaciones_Categorias1_idx` (`Categorias_idCategorias` ASC) VISIBLE,
  CONSTRAINT `fk_Publicaciones_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicaciones_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT(1000) NOT NULL,
  `fecha` DATE NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Publicaciones_idPublicaciones` INT NOT NULL,
  PRIMARY KEY (`idComentarios`),
  INDEX `fk_Comentarios_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Comentarios_Publicaciones1_idx` (`Publicaciones_idPublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Publicaciones1`
    FOREIGN KEY (`Publicaciones_idPublicaciones`)
    REFERENCES `mydb`.`Publicaciones` (`idPublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Insertar 15 usuarios
INSERT INTO Usuario (nombre, apellidos, Correo_electronico, genero, fecha_nac, Usuario, contrasena, contacto) 
VALUES
('KEVIN', 'SEVILLA', 'K@2.COM', 'M', '1997-11-23', 'user1', 'password', '123456789'),
('ANDREA', 'HERRA', 'A@.com', 'F', '2000-04-30', 'user2', 'password', '987654321'),
('LUIS', 'PEZ', 'L@.com', 'Otro', '1995-06-15', 'userr3', 'password3', '555555555');
('KEVIN', 'SEVILLA', 'FK@2.COM', 'M', '1997-11-23', 'user1', 'password', '123456789'),
('ANDREA', 'HERRARTE', 'JA@.com', 'F', '2000-04-30', 'user2', 'password', '987654321'),
('LUIS', 'LOPEZ', 'OL@.com', 'Otro', '1995-06-15', 'userr3', 'password3', '555555555');
('KEVIN', 'JIMENEZ', 'K@2.COM', 'M', '1997-11-23', 'user1', 'password', '123456789'),
('ANDREA', 'LUIS', 'A@.com', 'F', '2000-04-30', 'user2', 'password', '987654321'),
('LUIS', 'CAX', 'L@.com', 'Otro', '1995-06-15', 'userr3', 'password3', '555555555');
('KEVIN', 'SIMON', 'K@2.COM', 'M', '1997-11-23', 'user1', 'password', '123456789'),
('ANDREA', 'JATE', 'A@.com', 'F', '2000-04-30', 'user2', 'password', '987654321'),
('LUIS', 'PAN', 'L@.com', 'Otro', '1995-06-15', 'userr3', 'password3', '555555555');
('KEVIN', 'XOL', 'K@2.COM', 'M', '1997-11-23', 'user1', 'password', '123456789'),
('ANDREA', 'CASIMIRO', 'A@.com', 'F', '2000-04-30', 'user2', 'password', '987654321'),
('LUIS', 'BUENAVISTA', 'L@.com', 'Otro', '1995-06-15', 'userr3', 'password3', '555555555');

-- Insertar 30 publicaciones
INSERT INTO Publicaciones (fecha, descripcion, id_Usuario)
VALUES
('2024-04-01', 'HOLA 1', 1),
('2024-04-02', 'QUE TAL 2', 2),
('2024-04-02', 'QUE TAL 3', 2),
('2024-04-02', 'QUE TAL 4', 2),
('2024-04-02', 'QUE TAL 5', 2),
('2024-04-02', 'QUE TAL 6', 2),
('2024-04-02', 'QUE TAL 7', 2),
('2024-04-02', 'QUE TAL 8', 2),
('2024-04-02', 'QUE TAL 9', 2),
('2024-04-02', 'QUE TAL 10', 2),
('2024-04-02', 'QUE TAL 11', 2),
('2024-04-02', 'QUE TAL 12', 2),
('2024-04-02', 'QUE TAL 13', 2),
('2024-04-02', 'QUE TAL 14', 2),
('2024-04-02', 'QUE TAL 15', 2),
('2024-04-02', 'QUE TAL 16', 2),
('2024-04-02', 'QUE TAL 17', 2),
('2024-04-02', 'QUE TAL 18', 2),
('2024-04-02', 'QUE TAL 19', 2),
('2024-04-02', 'QUE TAL 20', 2),
('2024-04-02', 'QUE TAL 21', 2),
('2024-04-02', 'QUE TAL 22', 2),
('2024-04-02', 'QUE TAL 23', 2),
('2024-04-02', 'QUE TAL 24', 2),
('2024-04-02', 'QUE TAL 25', 2),
('2024-04-02', 'QUE TAL 26', 2),
('2024-04-02', 'QUE TAL 27', 2),
('2024-04-02', 'QUE TAL 28', 2),
('2024-04-02', 'QUE TAL 29', 2),
('2024-04-30', 'COMO ESTA 30', 30);

-- Insertar 15 categorias
INSERT INTO Categorias (nombre, id_principal, tipo)
VALUES
('Deportes', NULL, 0),
('Futbol', 1, 1),
('Viajes expres', 7, 1);
('Accion', NULL, 0),
('comedia', NULL, 0),
('diversion', 1, 0),
('romance', NULL, 0),
('muerte', NULL, 0),
('oceano', NULL, 0),
('marzo', NULL, 0),
('mesas', NULL, 0),
('piñatas', NULL, 0),
('postres', NULL, 0),
('polvo', NULL, 0),
('guatemala', NULL, 0),

-- Ingresar más de 5 categorias
INSERT INTO Categorias (nombre, id_principal, tipo)
VALUES
('Categoria6', NULL, 0),
('Subcategoria1', 6, 1),
('Subcategoria5', 6, 1);

-- Seleccionar publicaciones de 2 subcategorias
SELECT * FROM Publicaciones 
WHERE id IN (
    SELECT id_Publicacion FROM Categorias C
    INNER JOIN Publicaciones P ON C.id = P.id_Categoria
    WHERE tipo = 1 AND C.nombre IN ('Subcategoria1', 'Subcategoria2')
);

-- Seleccionar todas las publicaciones del usuario con id 8, 10, 12
SELECT * FROM Publicaciones WHERE id_Usuario IN (8, 10, 12);

-- Inner join entre publicaciones y usuarios
SELECT * FROM Publicaciones AS P
INNER JOIN Usuarios AS U ON P.id_Usuario = U.id;

-- Left join entre publicaciones y usuarios
SELECT * FROM Publicaciones AS P
LEFT JOIN Usuarios AS U ON P.id_Usuario = U.id;

-- Right join entre publicaciones y usuarios
SELECT * FROM Publicaciones AS P
RIGHT JOIN Usuarios AS U ON P.id_Usuario = U.id;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
