-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 11:43:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema miBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miBD` DEFAULT CHARACTER SET utf8 ;
USE `miBD` ;

-- -----------------------------------------------------
-- Table `miBD`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Productos` (
  `id_Productos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Precio_Actual` VARCHAR(45) NULL,
  `Stonck` VARCHAR(45) NULL,
  `Nombre_del_Producto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Proveedores` (
  `id_Proveedores` INT NOT NULL,
  `DPI` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Pagina_Web` VARCHAR(45) NULL,
  `Proveedorescol` VARCHAR(45) NULL,
  `Productos_id_Productos` INT NOT NULL,
  PRIMARY KEY (`id_Proveedores`),
  INDEX `fk_Proveedores_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `miBD`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Direccion` (
  `id_Direccion` INT NOT NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero` VARCHAR(45) NULL,
  `Comuna` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Ventas` (
  `id_Ventas` INT NOT NULL,
  `Fecha` VARCHAR(45) NULL,
  `Cliente` VARCHAR(45) NULL,
  `Descuento` VARCHAR(45) NULL,
  `Monto_Final` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Ventas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Clientes` (
  `id_Clientes` INT NOT NULL,
  `DPI` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono(s)` VARCHAR(45) NULL,
  `Direccion_id_Direccion` INT NOT NULL,
  `Ventas_id_Ventas` INT NOT NULL,
  PRIMARY KEY (`id_Clientes`),
  INDEX `fk_Clientes_Direccion1_idx` (`Direccion_id_Direccion` ASC) VISIBLE,
  INDEX `fk_Clientes_Ventas1_idx` (`Ventas_id_Ventas` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Direccion1`
    FOREIGN KEY (`Direccion_id_Direccion`)
    REFERENCES `miBD`.`Direccion` (`id_Direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_Ventas1`
    FOREIGN KEY (`Ventas_id_Ventas`)
    REFERENCES `miBD`.`Ventas` (`id_Ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Categoria` (
  `id_Categoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Detalle_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Detalle_Venta` (
  `id_Detalle_Venta` INT NOT NULL,
  `Precio_Venta` VARCHAR(45) NULL,
  `Cantidad_Venta` VARCHAR(45) NULL,
  `Monto_total_por_producto` VARCHAR(45) NULL,
  `Ventas_id_Ventas` INT NOT NULL,
  `Productos_id_Productos` INT NOT NULL,
  PRIMARY KEY (`id_Detalle_Venta`),
  INDEX `fk_Detalle_Venta_Ventas1_idx` (`Ventas_id_Ventas` ASC) VISIBLE,
  INDEX `fk_Detalle_Venta_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Venta_Ventas1`
    FOREIGN KEY (`Ventas_id_Ventas`)
    REFERENCES `miBD`.`Ventas` (`id_Ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Venta_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `miBD`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miBD`.`Productos_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miBD`.`Productos_has_Categoria` (
  `Productos_id_Productos` INT NOT NULL,
  `Categoria_id_Categoria` INT NOT NULL,
  PRIMARY KEY (`Productos_id_Productos`, `Categoria_id_Categoria`),
  INDEX `fk_Productos_has_Categoria_Categoria1_idx` (`Categoria_id_Categoria` ASC) VISIBLE,
  INDEX `fk_Productos_has_Categoria_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Categoria_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `miBD`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_id_Categoria`)
    REFERENCES `miBD`.`Categoria` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
