-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 10:55:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BLOG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BLOG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BLOG` DEFAULT CHARACTER SET utf8 ;
USE `BLOG` ;

-- -----------------------------------------------------
-- Table `BLOG`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BLOG`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `BLOG`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `genero` INT NULL,
  `fecha_nacimiento` DATE NULL,
  `password` INT NULL,
  `contacto` VARCHAR(10) NOT NULL,
  `usuarioscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BLOG`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BLOG`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `BLOG`.`publicaciones` (
  `idpublicaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `tipo_publicacion` MEDIUMTEXT NULL,
  `contenido` TEXT(500) NULL,
  `idusuarios` INT NOT NULL,
  PRIMARY KEY (`idpublicaciones`),
  INDEX `fk_publicaciones_usuarios_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuarios`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `BLOG`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BLOG`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BLOG`.`categorias` ;

CREATE TABLE IF NOT EXISTS `BLOG`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_principal` INT NOT NULL,
  `tipo` INT NULL,
  `idpublicaciones` INT NOT NULL,
  PRIMARY KEY (`idcategorias`),
  INDEX `fk_categorias_publicaciones1_idx` (`idpublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_publicaciones1`
    FOREIGN KEY (`idpublicaciones`)
    REFERENCES `BLOG`.`publicaciones` (`idpublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BLOG`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BLOG`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `BLOG`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT(500) NULL,
  `fecha` DATE NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `idpublicaciones` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`idpublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `BLOG`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`idpublicaciones`)
    REFERENCES `BLOG`.`publicaciones` (`idpublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
