-- Norberto Raymundo Arreaga Sánchez -- 

-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 14:42:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresaBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresaBD` DEFAULT CHARACTER SET utf8 ;
USE `empresaBD` ;

-- -----------------------------------------------------
-- Table `empresaBD`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT,
  `DPI` VARCHAR(13) NULL,
  `Nombre` VARCHAR(30) NULL,
  `Direccion` VARCHAR(50) NULL,
  `Telefono` VARCHAR(8) NULL,
  `PaginaWeb` VARCHAR(50) NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `DPI` VARCHAR(13) NULL,
  `Nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NULL,
  `Descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NULL,
  `PrecioActual` DECIMAL(10,2) NULL,
  `Stock` INT NULL,
  `Categorias_idCategorias` INT NOT NULL,
  `Proveedores_idProveedores` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `Categorias_idCategorias`, `Proveedores_idProveedores`),
  INDEX `fk_Productos_Categorias1_idx` (`Categorias_idCategorias` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedores1_idx` (`Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `empresaBD`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `empresaBD`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Descuento` DECIMAL(10,2) NULL,
  `MontoFinal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idVentas`, `Clientes_idClientes`),
  INDEX `fk_Ventas_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `empresaBD`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`DetallesVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`DetallesVentas` (
  `Productos_idProductos` INT NOT NULL,
  `Productos_Categorias_idCategorias` INT NOT NULL,
  `Productos_Proveedores_idProveedores` INT NOT NULL,
  `Ventas_idVentas` INT NOT NULL,
  `Ventas_Clientes_idClientes` INT NOT NULL,
  `PrecioVenta` DECIMAL(10,2) NULL,
  `CantidadVendida` INT NULL,
  `MontoTotalPorProducto` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Productos_idProductos`, `Productos_Categorias_idCategorias`, `Productos_Proveedores_idProveedores`, `Ventas_idVentas`, `Ventas_Clientes_idClientes`),
  INDEX `fk_Productos_has_Ventas_Ventas1_idx` (`Ventas_idVentas` ASC, `Ventas_Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Productos_has_Ventas_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Categorias_idCategorias` ASC, `Productos_Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Ventas_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Categorias_idCategorias` , `Productos_Proveedores_idProveedores`)
    REFERENCES `empresaBD`.`Productos` (`idProductos` , `Categorias_idCategorias` , `Proveedores_idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Ventas_Ventas1`
    FOREIGN KEY (`Ventas_idVentas` , `Ventas_Clientes_idClientes`)
    REFERENCES `empresaBD`.`Ventas` (`idVentas` , `Clientes_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(30) NULL,
  `Numero` INT NULL,
  `Comuna` VARCHAR(30) NULL,
  `Ciudad` VARCHAR(30) NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idDireccion`, `Clientes_idClientes`),
  INDEX `fk_Direccion_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `empresaBD`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaBD`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaBD`.`Contacto` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `Telefono` VARCHAR(8) NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idContacto`, `Clientes_idClientes`),
  INDEX `fk_Contacto_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Contacto_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `empresaBD`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
