-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 00:33:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
usuarios
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog_disenio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog_disenio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog_disenio` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `blog_disenio` ;

-- -----------------------------------------------------
-- Table `blog_disenio`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog_disenio`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `blog_disenio`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `usuarios` VARCHAR(45) NULL,
  `genero` INT NULL,
  `fecha_nacimiento` DATE NULL,
  `password` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `usuarioscol_UNIQUE` (`usuarios` ASC) VISIBLE)
ENGINE = InnoDB;
ALTER TABLE `blog_disenio`.`usuarios`
CHANGE COLUMN `usuarios` `nombre_usuario` VARCHAR(45) NULL;
INSERT INTO `blog_disenio`.`usuarios` 
(`nombre`, `apellidos`, `correo_electronico`, `nombre_usuario`, `genero`, `fecha_nacimiento`, `password`, `contacto`) 
VALUES
('Juan', 'Pérez', 'juan@example.com', 'juap', 1, '1990-05-15', 'contrasena123', '123456789'),
('María', 'Gómez', 'maria@example.com', 'magz', 2, '1988-09-20', 'maria123', '987654321'),
('Pedro', 'Sánchez', 'pedro@example.com', 'pesa', 1, '1995-03-10', 'pedro456', '456789123'),
('Laura', 'López', 'laura@example.com', 'lalo', 2, '1992-11-08', 'laura789', '321654987'),
('Carlos', 'Martínez', 'carlos@example.com', 'cama', 1, '1987-07-25', 'carlos567', '789456123'),
('Ana', 'Rodríguez', 'ana@example.com', 'anro', 2, '1998-02-18', 'ana234', '654123789'),
('David', 'Hernández', 'david@example.com', 'dahz', 1, '1993-04-30', 'david789', '159357486'),
('Sofía', 'García', 'sofia@example.com', 'soga', 2, '1991-12-05', 'sofia321', '852369741'),
('Javier', 'Díaz', 'javier@example.com', 'jadi', 1, '1989-08-12', 'javier456', '369852147'),
('Elena', 'Fernández', 'elena@example.com', 'elfe', 2, '1994-06-22', 'elena987', '147258369'),
('Diego', 'Moreno', 'diego@example.com', 'dimr', 1, '1996-10-28', 'diego123', '963852741'),
('Lucía', 'Navarro', 'lucia@example.com', 'luna', 2, '1997-07-17', 'lucia456', '741852963'),
('Miguel', 'Ruiz', 'miguel@example.com', 'miru', 1, '1990-03-05', 'miguel789', '258147369'),
('Carmen', 'Santiago', 'carmen@example.com', 'casa', 2, '1986-09-14', 'carmen234', '123456789'),
('Raúl', 'López', 'raul@example.com', 'ralo', 1, '1985-01-30', 'raul567', '987654321');


-- -----------------------------------------------------
-- Table `blog_disenio`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog_disenio`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `blog_disenio`.`publicaciones` (
  `id_publicaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `titulo_publicacion` MEDIUMTEXT NULL,
  `descripcion_contenido` TEXT(500) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id_publicaciones`),
  INDEX `fk_publicaciones_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `blog_disenio`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `blog_disenio`.`publicaciones` 
(`fecha`, `titulo_publicacion`, `descripcion_contenido`, `usuarios_id`) 
VALUES
('2024-04-16', 'Las nuevas tendencias en la tecnología', 'Descubre las últimas novedades en tecnología y cómo están impactando en nuestra vida cotidiana.', 1),
('2024-04-15', 'Recetas saludables para el verano', 'Prepara platos deliciosos y saludables para disfrutar durante los días calurosos de verano.', 2),
('2024-04-14', 'Consejos para mejorar tu productividad', 'Aumenta tu eficiencia y logra más en menos tiempo con estos consejos prácticos.', 3),
('2024-04-13', 'El arte de la fotografía urbana', 'Explora la belleza oculta de la vida urbana a través del lente de fotógrafos expertos.', 4),
('2024-04-12', 'Viajes económicos: destinos sorprendentes', 'Descubre destinos increíbles que puedes visitar sin gastar una fortuna en tus próximas vacaciones.', 5),
('2024-04-11', 'Diseño de interiores: tendencias modernas', 'Explora las últimas tendencias en diseño de interiores y cómo puedes aplicarlas en tu hogar.', 6),
('2024-04-10', 'Consejos para cuidar tu jardín en primavera', 'Aprende técnicas y trucos para mantener tu jardín hermoso y saludable durante la temporada de primavera.', 7),
('2024-04-09', 'Los mejores consejos para mejorar tus habilidades culinarias', 'Descubre secretos de chefs profesionales para mejorar tus habilidades en la cocina y sorprender a tus invitados.', 8),
('2024-04-08', 'Cómo empezar un negocio online desde cero', 'Aprende los pasos clave para lanzar un negocio online exitoso, desde la planificación hasta la promoción.', 9),
('2024-04-07', 'Los beneficios de practicar yoga regularmente', 'Descubre cómo el yoga puede mejorar tu salud física, mental y emocional, y cómo empezar tu propia práctica en casa.', 10),
('2024-04-06', 'Consejos para mejorar tu productividad laboral', 'Aprende estrategias efectivas para aumentar tu productividad en el trabajo y lograr tus objetivos de manera más eficiente.', 11),
('2024-04-05', 'Las mejores películas para ver en familia', 'Descubre películas para toda la familia que son perfectas para disfrutar juntos en una noche de cine en casa.', 12),
('2024-04-04', 'Ideas creativas para decorar tu espacio de trabajo en casa', 'Inspírate con estas ideas creativas para personalizar y decorar tu espacio de trabajo en casa y hacerlo más productivo y acogedor.', 13),
('2024-04-03', 'Consejos para una alimentación saludable durante el embarazo', 'Aprende qué alimentos son esenciales para una dieta saludable durante el embarazo y cómo mantener un estilo de vida activo y equilibrado.', 14),
('2024-04-02', 'Cómo cultivar un jardín de hierbas en casa', 'Descubre todo lo que necesitas saber para cultivar y cuidar un jardín de hierbas frescas en tu hogar, desde la siembra hasta la cosecha.', 15),
('2024-04-01', 'Ideas para organizar un picnic perfecto en el parque', 'Aprende a planificar y preparar un picnic increíble en el parque con amigos y familiares, con deliciosos platos y actividades divertidas al aire libre.', 1),
('2024-03-31', 'Consejos para mejorar tu técnica de fotografía', 'Aprende técnicas y trucos para mejorar tu habilidad fotográfica y capturar imágenes impresionantes en cualquier situación.', 2),
('2024-03-30', 'Los beneficios de la meditación para reducir el estrés', 'Descubre cómo la meditación puede ayudarte a reducir el estrés, calmar tu mente y mejorar tu bienestar general en la vida cotidiana.', 3),
('2024-03-29', 'Cómo planificar un viaje de mochilero económico', 'Aprende a planificar un emocionante viaje de mochilero con un presupuesto limitado, incluyendo consejos para ahorrar dinero en alojamiento, transporte y comida.', 4),
('2024-03-28', 'Recetas saludables y fáciles para la hora del almuerzo', 'Descubre deliciosas y nutritivas recetas para preparar almuerzos rápidos y saludables que puedes disfrutar en casa o llevar al trabajo.', 5),
('2024-03-27', 'Consejos para una piel saludable y radiante', 'Aprende los secretos para mantener tu piel saludable y radiante en cualquier época del año, con una rutina de cuidado de la piel simple pero efectiva.', 6),
('2024-03-26', 'Los mejores destinos para un viaje de aventura', 'Descubre emocionantes destinos alrededor del mundo ideales para viajeros aventureros, con actividades como senderismo, buceo, y más.', 7),
('2024-03-25', 'Cómo construir una red profesional sólida', 'Aprende estrategias para construir y mantener una red profesional sólida que te ayude a avanzar en tu carrera y alcanzar tus metas laborales.', 8),
('2024-03-24', 'Ideas para organizar una fiesta temática inolvidable', 'Inspírate con estas ideas creativas para organizar una fiesta temática única y divertida que tus invitados recordarán por mucho tiempo.', 9),
('2024-03-23', 'Consejos para mejorar tu técnica de dibujo', 'Aprende técnicas y ejercicios para mejorar tu habilidad de dibujo y expresar tu creatividad a través del arte.', 10),
('2024-03-22', 'Recetas deliciosas para consentir a tu mascota', 'Descubre recetas caseras y saludables para preparar deliciosos premios y comidas caseras para consentir a tu mascota y mantenerla feliz y saludable.', 11),
('2024-03-21', 'Consejos para decorar un dormitorio pequeño', 'Aprende trucos y consejos inteligentes para maximizar el espacio y decorar un dormitorio pequeño de manera funcional y estética.', 12),
('2024-03-20', 'Cómo empezar un huerto urbano en tu balcón', 'Descubre cómo cultivar tus propias frutas, verduras y hierbas frescas en un huerto urbano en tu balcón, incluso si tienes poco espacio.', 13),
('2024-03-19', 'Ideas para un día de spa relajante en casa', 'Crea un día de spa relajante en la comodidad de tu hogar con estas ideas para tratamientos de belleza, relajación y cuidado personal.', 14),
('2024-03-18', 'Los mejores libros de autoayuda para leer este año', 'Descubre libros inspiradores y motivadores de autoayuda que te ayudarán a crecer personalmente y alcanzar tus metas en la vida.', 15);



-- -----------------------------------------------------
-- Table `blog_disenio`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog_disenio`.`categorias` ;

CREATE TABLE IF NOT EXISTS `blog_disenio`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `id_principal` INT NOT NULL,
  `publicaciones_idpublicaciones` INT NOT NULL,
  PRIMARY KEY (`idcategorias`),
  INDEX `fk_categorias_publicaciones1_idx` (`publicaciones_idpublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_publicaciones1`
    FOREIGN KEY (`publicaciones_idpublicaciones`)
    REFERENCES `blog_disenio`.`publicaciones` (`id_publicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Insertamos las categorías
INSERT INTO `blog_disenio`.`categorias` 
(`nombre`, `tipo`, `id_principal`, `publicaciones_idpublicaciones`) 
VALUES
('Tecnología', 1, 1, 31),
('Recetas', 2, 2, 32),
('Productividad', 3, 3, 33),
('Fotografía', 4, 4, 34),
('Viajes', 5, 5, 35),
('Diseño de interiores', 6, 6, 36),
('Jardinería', 7, 7, 37),
('Cocina', 8, 8, 38),
('Negocios online', 9, 9, 39),
('Yoga', 10, 10, 40),
('Cine familiar', 11, 11, 41),
('Decoración', 12, 12, 42),
('Embarazo', 13, 13, 43),
('Jardinería casera', 14, 14, 44),
('Picnic', 15, 15, 45);



-- -----------------------------------------------------
-- Table `blog_disenio`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog_disenio`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `blog_disenio`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT(500) NULL,
  `fecha` DATE NULL,
  `usuarios_id` INT NOT NULL,
  `publicaciones_idpublicaciones` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`publicaciones_idpublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `blog_disenio`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicaciones_idpublicaciones`)
    REFERENCES `blog_disenio`.`publicaciones` (`id_publicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `blog_disenio`.`comentarios` 
(`comentario`, `fecha`, `usuarios_id`, `publicaciones_idpublicaciones`) 
VALUES
('¡Excelente artículo! Me encantó la información proporcionada.', '2024-04-16', 1, 31),
('Gracias por compartir estas recetas, definitivamente las probaré.', '2024-04-15', 2, 32),
('Los consejos de productividad son muy útiles, gracias por compartirlos.', '2024-04-14', 3, 33),
('Las imágenes de fotografía urbana son realmente impresionantes.', '2024-04-13', 4, 34),
('¡Qué inspiradores son los destinos de viaje que has mencionado!', '2024-04-12', 5, 35),
('Me encanta el diseño de interiores, ¡gracias por las ideas!', '2024-04-11', 6, 36),
('Estos consejos para el cuidado del jardín son justo lo que necesitaba.', '2024-04-10', 7, 37);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
