-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 20:28:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `fecha_nac` DATE NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `table1col` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `id_publicacion` INT NOT NULL,
  `fecha` DATE NULL,
  `titulo_ublicacion` MEDIUMTEXT NULL,
  `contenido` TEXT(500) NULL,
  `publicacionescol` VARCHAR(45) NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_publicaciones_usuario_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuario`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `mydb`.`usuario` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_principal` INT NOT NULL,
  `tipo` INT NULL,
  `id_publicacion` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categorias_publicaciones1_idx` (`id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_publicaciones1`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `mydb`.`publicaciones` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id_comentarios` INT NOT NULL,
  `comentario` TEXT(500) NULL,
  `fecha` DATE NULL,
  `id_usuarios` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  PRIMARY KEY (`id_comentarios`),
  INDEX `fk_comentarios_usuario1_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `mydb`.`usuario` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `mydb`.`publicaciones` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



